application: teamcitymonitor
version: 3
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles
      
- url: .*
  script: main.py
 
builtins:
  - datastore_admin: on
  
